Repository runtimeverification/mir-semantics, pull requests merged in 2023-11, with the labels that each got.

#244 Added evaluation of tuples.
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-types.md
  kmir/src/tests/integration/test-data/handwritten-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-rust/assert_eq.mir
  kmir/src/tests/integration/test-data/handwritten-rust/assert_eq.rs
  kmir/src/tests/integration/test-data/handwritten-rust/tuples-simple.mir
  kmir/src/tests/integration/test-data/handwritten-rust/tuples-simple.rs
  kmir/src/tests/integration/test_run.py
Labels: kmir-run

#245 Field evaluation for tuples
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-types.md
  kmir/src/tests/integration/test-data/compiletest-run-fail.tsv
Labels: kmir-run

#243 Semantics/recursion
  kmir/k-src/mir-configuration.md
  kmir/k-src/mir.md
  kmir/src/tests/integration/proofs/simple-spec.k
  kmir/src/tests/integration/test-data/compiletest-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-rust/fibonacci.mir
  kmir/src/tests/integration/test-data/handwritten-rust/fibonacci.rs
  kmir/src/tests/integration/test-data/handwritten-rust/mutual_recursion.mir
  kmir/src/tests/integration/test-data/handwritten-rust/mutual_recursion.rs
  kmir/src/tests/integration/test-data/handwritten-rust/recursion-simple.mir
  kmir/src/tests/integration/test-data/handwritten-rust/recursion-simple.rs
Labels: kmir-run

#239 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#247 Added `no_expand_macros` flag for `krun`
  kmir/src/kmir/kmir.py
Labels: automerge

#248 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#249 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#251 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#250 `Option` evaluation
  kmir/k-src/mir-lexer-syntax.md
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-terminator.md
  kmir/k-src/mir-types.md
  kmir/k-src/mir.md
  kmir/src/tests/integration/test-data/compiletest-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-rust/option-construction.mir
  kmir/src/tests/integration/test-data/handwritten-rust/option-construction.rs
  kmir/src/tests/integration/test-data/handwritten-rust/recursion-simple-match.mir
  kmir/src/tests/integration/test-data/handwritten-rust/recursion-simple-match.rs
Labels: kmir-run

#253 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#256 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#258 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#259 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#260 Updating prover
  kmir/k-src/mir.md
  kmir/src/kmir/__main__.py
  kmir/src/kmir/cli.py
  kmir/src/kmir/utils.py
  kmir/src/tests/integration/proofs/empty-program.k
  kmir/src/tests/integration/proofs/empty-program.mir
  kmir/src/tests/integration/proofs/empty-program.rs
  kmir/src/tests/integration/proofs/lemmas.k
  kmir/src/tests/integration/proofs/simple-spec.k
  kmir/src/tests/integration/test_prove.py
Labels: kmir-prove

#262 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#265 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge
