Repository runtimeverification/mir-semantics, pull requests merged in 2023-08, with the labels that each got.

#185 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#184 Update dependency: deps/pyk_release
  deps/pyk_release
  kmir/flake.lock
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#194 Feature/kup
  .flake8
  flake.lock
  flake.nix
  kmir/Makefile
  kmir/flake.lock
  kmir/flake.nix
  kmir/poetry.lock
  kmir/src/kmir/__main__.py
  kmir/src/kmir/kmir.py
Labels: automerge

#196 Removed parenthesis from token attribute to match changing k
  kmir/k-src/mir-lexer-syntax.md
Labels: automerge, bug

#192 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#191 Update dependency: deps/pyk_release
  .github/workflows/update-version.yml
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/flake.lock
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#195 Default definition paths
  kmir/.gitignore
  kmir/Makefile
  kmir/README.md
  kmir/poetry.lock
  kmir/set_env.sh
Labels: automerge

#201 Update dependency: deps/k_release
  deps/k_release
Labels: automerge

#205 CI update flake when pyk/k is updated
  .github/workflows/update-version.yml
  flake.lock
  flake.nix
Labels: automerge

#197 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#199 Nix ci
  .github/workflows/test.yml
  flake.nix
  kmir/README.md
  kmir/src/tests/nix/Makefile
  kmir/src/tests/nix/arithm-simple.parse.out
  kmir/src/tests/nix/arithm-simple.run.out
  kmir/src/tests/nix/nix-tests.sh
Labels: kmir-tests

#206 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge
