Repository runtimeverification/mir-semantics, pull requests merged in 2023-10, with the labels that each got.

#217 Removing `init` from help menu
  kmir/src/kmir/__main__.py
Labels: automerge

#210 Update dependency: deps/k_release
  deps/k_release
  flake.lock
  flake.nix
  kmir/k-src/mir-configuration.md
  kmir/poetry.lock
  kmir/smoke/benchmark.run.const-arithm-simple.out
  kmir/smoke/benchmark.run.test-binop.out
  kmir/smoke/benchmark.run.test-sum-to-n.out
  kmir/src/tests/nix/arithm-simple.run.out
Labels: automerge

#211 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/tests/conftest.py
  kmir/src/tests/utils.py
Labels: automerge

#221 Fixed `make clean`
  kmir/Makefile
Labels: bug

#222 Added `RigidTy` for integers and boolean
  kmir/k-src/mir-lexer-syntax.md
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-types.md
  kmir/poetry.lock
Labels: kmir-parse

#225 `clean` before `build`
  kmir/Makefile
Labels: bug

#227 Parse failing fix 1
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-syntax.md
  kmir/k-src/mir-terminator.md
  kmir/poetry.lock
  kmir/src/tests/integration/test-data/compiletest-parse-fail.tsv
Labels: kmir-parse

#226 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#230 Syntax/rigid ty update 1
  kmir/k-src/mir-types.md
  kmir/src/tests/integration/test-data/compiletest-parse-fail.tsv
Labels: kmir-parse

#231 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#232 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#237 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#238 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#241 Semantics/min max
  kmir/k-src/mir-rvalue.md
  kmir/src/tests/integration/test-data/compiletest-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-rust/primitive-type-bounds.mir
  kmir/src/tests/integration/test-data/handwritten-rust/primitive-type-bounds.rs
Labels: kmir-run

#216 Rules to process `Ref` and `Deref` `RValues`
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir.md
  kmir/src/tests/integration/test-data/compiletest-run-fail.tsv
  kmir/src/tests/integration/test-data/handwritten-rust/double-ref-deref.mir
  kmir/src/tests/integration/test-data/handwritten-rust/double-ref-deref.rs
  kmir/src/tests/integration/test-data/handwritten-rust/ref-deref.mir
  kmir/src/tests/integration/test-data/handwritten-rust/ref-deref.rs
  kmir/src/tests/integration/test-data/handwritten-rust/strange-ref-deref.mir
  kmir/src/tests/integration/test-data/handwritten-rust/strange-ref-deref.rs
Labels: kmir-run
