Repository runtimeverification/mir-semantics, pull requests merged in 2023-12, with the labels that each got.

#275 Adding version
  package/version
Labels: automerge

#272 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
Labels: automerge

#277 Hotfix: Docker correct linking to `K_COMMIT`
  .github/workflows/master-push.yml
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge, bug

#276 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#279 Docker documentation correction
  README.md
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge, documentation

#285 Booster support
  kmir/Makefile
  kmir/kbuild.toml
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/tests/integration/test_prove.py
  package/version
Labels: automerge, kmir-prove

#281 Included `#panic` and `#internalPanic` in terminal rules.
  kmir/k-src/mir.md
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/kmir.py
  kmir/src/kmir/utils.py
  package/version
Labels: automerge, kmir-prove

#289 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#270 CLI and test improvements
  kmir/Makefile
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/cli.py
  kmir/src/tests/nix/nix-tests.sh
  package/version
Labels: automerge, kmir-tests

#293 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#295 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#299 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#294 Create GLR parser at build time
  flake.nix
  kmir/Makefile
  kmir/kbuild.toml
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/cli.py
  kmir/src/kmir/kmir.py
  package/version
Labels: automerge, k-tooling

#300 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#298 Capture errors that could occur while printing error information
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/utils.py
  package/version
Labels: automerge, kmir-prove

#301 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#302 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#304 Remove `Local2Int` function for performance and stability
  kmir/k-src/mir-configuration.md
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-types.md
  kmir/k-src/mir.md
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/tests/integration/test-data/prove-rs/simple-spec.k
  kmir/src/tests/nix/sum-to-n.run.out
  package/version
Labels: automerge, kmir-prove
