Repository runtimeverification/mir-semantics, pull requests merged in 2024-02, with the labels that each got.

#323 Updates to proof feedback.
  README.md
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/prove.py
  kmir/src/tests/conftest.py
  kmir/src/tests/integration/test-data/prove-rs/show.k
  kmir/src/tests/integration/test-data/prove-rs/verify.k
  kmir/src/tests/integration/test-data/show-proof
  kmir/src/tests/integration/test-data/show/SHOW.fail1.expected
  kmir/src/tests/integration/test-data/show/SHOW.pass1.expected
  kmir/src/tests/integration/test_prove.py
  kmir/src/tests/integration/utils.py
  package/version
Labels: kmir-tests, kmir-prove

#314 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/tests/integration/test-data/prove-rs/empty-program.k
  package/version
Labels: automerge

#324 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#329 Replace usages of `priorities`, `require`, and `import`
  kmir/k-src/mir-assert.md
  kmir/k-src/mir-configuration.md
  kmir/k-src/mir-operand.md
  kmir/k-src/mir-place.md
  kmir/k-src/mir-rvalue.md
  kmir/k-src/mir-statement.md
  kmir/k-src/mir-syntax.md
  kmir/k-src/mir-terminator.md
  kmir/k-src/mir-types.md
  kmir/k-src/mir.md
  kmir/k-src/panics.md
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#325 Add feature: prove a single claim in `kmir prove`
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/cli.py
  kmir/src/kmir/kmir.py
  kmir/src/kmir/prove.py
  package/version
Labels: k-tooling, kmir-prove

#326 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/kmir.py
  kmir/src/tests/nix/sum-to-n.run.out
  package/version
Labels: automerge

#331 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#332 Update dependency: deps/pyk_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#333 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/kmir.py
  package/version
Labels: automerge

#334 Update dependency: deps/pyk_release
  .github/workflows/master-push.yml
  .github/workflows/test.yml
  .github/workflows/update-version.yml
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge
