Repository runtimeverification/mir-semantics, pull requests merged in 2024-01, with the labels that each got.

#307 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#305 More proofs
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/tests/integration/test-data/handwritten-prove-fail.tsv
  kmir/src/tests/integration/test-data/prove-rs/add.k
  kmir/src/tests/integration/test-data/prove-rs/add.mir
  kmir/src/tests/integration/test-data/prove-rs/add.rs
  kmir/src/tests/integration/test-data/prove-rs/lemmas.k
  kmir/src/tests/integration/test-data/prove-rs/simple-spec.k
  kmir/src/tests/integration/test-data/prove-rs/verify.k
  kmir/src/tests/integration/test_prove.py
  package/version
Labels: automerge, kmir-prove

#291 Kompile uses new type inference algorithm
  kmir/kbuild.toml
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#311 Update dependency: deps/pyk_release
  deps/k_release
  deps/pyk_release
  flake.lock
  flake.nix
  kmir/poetry.lock
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  package/version
Labels: automerge

#312 Refactor/kmir class
  README.md
  demo/SIMPLE-SPEC.statement.1/kcfg/kcfg.json
  demo/SIMPLE-SPEC.statement.1/kcfg/nodes/1.json
  demo/SIMPLE-SPEC.statement.1/kcfg/nodes/2.json
  demo/SIMPLE-SPEC.statement.1/kcfg/nodes/3.json
  demo/SIMPLE-SPEC.statement.1/proof.json
  demo/simple-spec.k
  demo/verify.k
  kmir/kbuild.toml
  kmir/pyproject.toml
  kmir/src/kmir/__init__.py
  kmir/src/kmir/__main__.py
  kmir/src/kmir/cli.py
  kmir/src/kmir/kmir.py
  kmir/src/kmir/parse.py
  kmir/src/kmir/preprocessor.py
  kmir/src/kmir/prove.py
  kmir/src/kmir/run.py
  kmir/src/kmir/semantics.py
  kmir/src/kmir/utils.py
  kmir/src/tests/conftest.py
  kmir/src/tests/integration/test_parse.py
  kmir/src/tests/integration/test_prove.py
  kmir/src/tests/integration/test_run.py
  kmir/src/tests/nix/sum-to-n.parse.out
  kmir/src/tests/nix/sum-to-n.run.out
  kmir/src/tests/unit/add.add.-------.renumber.0.mir
  kmir/src/tests/unit/add.add.006-000.runtime-optimized.after.mir
  kmir/src/tests/unit/add.mir
  kmir/src/tests/unit/add.rs
  kmir/src/tests/unit/test_preprocess.py
  package/version
Labels: k-tooling, refactor
